'use client'

import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';


import "../Assets/css/icons.css";
import "../Assets/css/global.css";
import "../Assets/css/pages.css";
import "../index.scss";
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,title}) {
  return (
    <html lang="en">
      <head>
        <title>{title}</title>
      </head>
      <body className="flex-1 flex">
        {children}
      </body>
    </html>
  )
};
